import { useMemo, useState } from "react";
import { BrowserRouter, NavLink, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { Bell, ChevronDown, CircleUserRound, Edit3, Eye, Filter, Home as HomeIcon, Leaf, LineChart, MapPin, Menu, MessageCircle, Package, Plus, Search, Settings, ShoppingBasket, Store, Truck, Warehouse, X } from "lucide-react";
import "@/App.css";

const navItems = [
  ["/", "Home", HomeIcon], ["/marketplace", "Marketplace", Store], ["/prices", "Market Prices", LineChart],
  ["/produce", "My Produce", Leaf], ["/requests", "Buyer Requests", ShoppingBasket], ["/storage", "Storage", Warehouse],
  ["/transport", "Transport", Truck], ["/orders", "Orders", Package], ["/messages", "Messages", MessageCircle], ["/profile", "Profile", CircleUserRound],
];
const produce = [{ name: "Tomato", detail: "Grade A • Organic", amount: "800", place: "Farm Storage 1", icon: "nutrition", tone: "red" }, { name: "Onion", detail: "Red • Standard", amount: "500", place: "Warehouse B", icon: "psychiatry", tone: "gold" }, { name: "Potato", detail: "Russet • Premium", amount: "350", place: "Farm Storage 2", icon: "grain", tone: "stone" }];
const requests = [{ name: "Need 500 kg Tomato", detail: "Grade A Quality", meta: "Within 20 km (Delivery preferred)", time: "Posted 2 hours ago", tone: "red", verified: true }, { name: "Need 1,000 kg Onion", detail: "Standard Size", meta: "Pickup from farm", time: "Posted 5 hours ago", tone: "purple", verified: false }];

function Shell({ children }) {
  const [open, setOpen] = useState(false);
  const location = useLocation();
  return <div className="app-shell">
    <button className="mobile-menu" data-testid="mobile-menu-button" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X /> : <Menu />}</button>
    <aside className={open ? "sidebar is-open" : "sidebar"} data-testid="app-sidebar">
      <div className="brand"><div className="brand-mark"><Leaf size={18} /></div><div><strong>KrishiLink</strong><span>Agricultural Marketplace</span></div></div>
      <nav className="nav-list">{navItems.map(([to, label, Icon]) => <NavLink key={to} to={to} end={to === "/"} className={({ isActive }) => isActive ? "nav-item active" : "nav-item"} data-testid={`nav-${label.toLowerCase().replaceAll(" ", "-")}`} onClick={() => setOpen(false)}><Icon size={19} strokeWidth={1.8} /><span>{label}</span></NavLink>)}</nav>
      <button className="post-button" data-testid="sidebar-post-produce-button" onClick={() => window.location.assign("/produce?add=true")}><Plus size={18} /> Post Produce</button>
      <div className="sidebar-footer"><div className="avatar">AS</div><div><strong>Arjun Singh</strong><span>Farmer account</span></div><Settings size={16} /></div>
    </aside>
    <main className="main-content"><header className="topbar"><div className="crumb"><span>Workspace</span><ChevronDown size={14} /></div><div className="top-actions"><button data-testid="language-button" className="icon-button">EN</button><button data-testid="notifications-button" className="icon-button notification"><Bell size={19} /><i /></button><button data-testid="profile-menu-button" className="profile-trigger"><div className="avatar small">AS</div><span>Arjun Singh</span><ChevronDown size={14} /></button></div></header>{children}</main>
  </div>;
}

function PageHeader({ eyebrow, title, description, action }) { return <div className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description && <p className="page-description">{description}</p>}</div>{action}</div>; }
function Stat({ label, value, detail, tone = "green" }) { return <div className="stat" data-testid={`stat-${label.toLowerCase().replaceAll(" ", "-")}`}><div className={`stat-icon ${tone}`}><Leaf size={18} /></div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div>; }

function Home() { const navigate = useNavigate(); return <><PageHeader eyebrow="Overview / 01" title="Good morning, Arjun" description="Your harvest, marketplace activity, and next opportunities at a glance." action={<button className="primary-button" data-testid="home-post-produce-button" onClick={() => navigate("/produce?add=true")}><Plus size={18} /> Post Produce</button>} /><section className="stats-grid"><Stat label="Active stock" value="1,650 kg" detail="Across 3 produce lots" /><Stat label="Market value" value="₹82,400" detail="↑ 8.4% this week" tone="blue" /><Stat label="Open requests" value="24" detail="6 match your produce" tone="peach" /><Stat label="Next delivery" value="Tomorrow" detail="To Green Basket Co." tone="gold" /></section><div className="dashboard-grid"><section className="panel harvest-panel"><div className="section-heading"><div><p className="eyebrow">Inventory pulse</p><h2>Your produce</h2></div><NavLink to="/produce" data-testid="home-view-produce-link">View all <span>→</span></NavLink></div>{produce.map((item) => <div className="compact-row" key={item.name} data-testid={`home-produce-${item.name.toLowerCase()}-row`}><div className={`crop-icon ${item.tone}`}><Leaf size={19} /></div><div className="row-main"><strong>{item.name}</strong><span>{item.detail}</span></div><strong className="row-value">{item.amount} <small>kg</small></strong><span className="status-dot">Available</span></div>)}</section><section className="panel activity-panel"><div className="section-heading"><div><p className="eyebrow">Recent activity</p><h2>Stay in the loop</h2></div><Bell size={19} /></div>{["Tomato listing viewed by 3 buyers", "Order #KL-2048 is ready for pickup", "You matched with Green Basket Co."].map((x, i) => <div className="activity" key={x}><span className={`activity-mark mark-${i}`} /><div><strong>{x}</strong><small>{["12 minutes ago", "Yesterday, 4:30 PM", "Yesterday, 11:12 AM"][i]}</small></div></div>)}</section></div><section className="quote-band"><div><p className="eyebrow">Market insight</p><h2>“Better information makes for better harvests.”</h2><p>Tomato demand is up 12% in your region this week.</p></div><NavLink to="/prices" className="outline-button" data-testid="home-market-prices-link">Explore prices <LineChart size={16} /></NavLink></section></>; }

function Produce() { const [items, setItems] = useState(produce); const [showForm, setShowForm] = useState(false); const [sold, setSold] = useState([]); const add = () => { const name = prompt("Produce name"); if (name) setItems([...items, { name, detail: "Fresh stock", amount: "0", place: "Farm Storage 1", tone: "green" }]); }; return <><PageHeader eyebrow="Inventory / 04" title="My Produce" description={<>Total active stock: <b>1,650 kg</b></>} action={<button className="primary-button" data-testid="add-produce-button" onClick={() => { setShowForm(true); add(); }}><Plus size={18} /> Add Produce</button>} />{showForm && <div className="toast" data-testid="produce-success-message">Produce list updated <button data-testid="dismiss-toast-button" onClick={() => setShowForm(false)}>×</button></div>}<section className="produce-grid">{items.map((item) => <article className="produce-card" key={item.name}><div className="card-top"><div className={`crop-icon ${item.tone}`}><Leaf size={20} /></div><div><h3>{item.name}</h3><p>{item.detail}</p></div><span className="availability">Available</span></div><div className="amount">{item.amount} <small>kg</small></div><p className="location"><MapPin size={15} /> {item.place}</p><div className="card-actions"><button data-testid={`view-${item.name.toLowerCase()}-button`}><Eye size={16} /> View Lot</button><button className="square" data-testid={`edit-${item.name.toLowerCase()}-button`} aria-label={`Edit ${item.name}`}><Edit3 size={16} /></button></div><button className="sold-button" data-testid={`mark-${item.name.toLowerCase()}-sold-button`} onClick={() => setSold([...sold, item.name])}>{sold.includes(item.name) ? "Marked as sold" : "Mark as Sold"}</button></article>)}</section></>; }

function Requests() { const [filtered, setFiltered] = useState(requests); const apply = (e) => { e.preventDefault(); const crop = e.currentTarget.crop.value; setFiltered(crop === "All crops" ? requests : requests.filter((r) => r.name.toLowerCase().includes(crop.toLowerCase()))); }; return <><PageHeader eyebrow="Opportunities / 05" title="Buyer requests" description="Connect with buyers looking for specific produce in your area." /><form className="filter-bar" onSubmit={apply} data-testid="buyer-request-filter-form"><label>Crop type<select name="crop" data-testid="crop-type-select"><option>All crops</option><option>Tomato</option><option>Onion</option></select></label><label>Minimum quantity<input name="quantity" data-testid="minimum-quantity-input" type="number" placeholder="e.g. 100" /></label><label>Distance<select name="distance" data-testid="distance-select"><option>Within 50 km</option><option>Within 20 km</option><option>Anywhere</option></select></label><button className="secondary-button" data-testid="apply-filters-button"><Filter size={16} /> Apply filters</button></form><section className="request-grid">{filtered.map((r) => <article className="request-card" key={r.name}><div className="request-title"><div className={`crop-photo ${r.tone}`}><Leaf size={24} /></div><div><h3>{r.name}</h3><p>{r.detail}</p></div>{r.verified && <span className="verified">✓ Verified buyer</span>}</div><div className="request-meta"><span><MapPin size={16} /> {r.meta}</span><span><Bell size={15} /> {r.time}</span></div><button className="full-button" data-testid={`view-request-${r.name.split(" ").pop().toLowerCase()}-button`} onClick={() => alert(`Request details for ${r.name}`)}>View request <span>→</span></button></article>)}</section></>; }

function GenericPage({ title, eyebrow, description, icon: Icon = Package }) { return <><PageHeader eyebrow={eyebrow} title={title} description={description} action={<button className="primary-button" data-testid={`${title.toLowerCase().replaceAll(" ", "-")}-primary-button`}><Plus size={18} /> Create new</button>} /><div className="empty-panel" data-testid={`${title.toLowerCase().replaceAll(" ", "-")}-content`}><div className="empty-icon"><Icon size={25} /></div><h2>Your {title.toLowerCase()} workspace</h2><p>Keep your agricultural operations organized and connected from one calm, focused place.</p><button className="secondary-button"><Search size={16} /> Browse activity</button></div></>; }

function App() { return <BrowserRouter><Shell><Routes><Route path="/" element={<Home />} /><Route path="/produce" element={<Produce />} /><Route path="/requests" element={<Requests />} /><Route path="/marketplace" element={<GenericPage title="Marketplace" eyebrow="Discover / 02" description="Find trusted buyers, sellers, and fresh opportunities." icon={Store} />} /><Route path="/prices" element={<GenericPage title="Market Prices" eyebrow="Signals / 03" description="Track the latest rates for crops in your region." icon={LineChart} />} /><Route path="/storage" element={<GenericPage title="Storage" eyebrow="Logistics / 06" description="Manage where your harvest is kept and cared for." icon={Warehouse} />} /><Route path="/transport" element={<GenericPage title="Transport" eyebrow="Logistics / 07" description="Coordinate pickups and deliveries with confidence." icon={Truck} />} /><Route path="/orders" element={<GenericPage title="Orders" eyebrow="Operations / 08" description="Review every active and completed order." icon={Package} />} /><Route path="/messages" element={<GenericPage title="Messages" eyebrow="Connections / 09" description="Stay close to the people who move your produce." icon={MessageCircle} />} /><Route path="/profile" element={<GenericPage title="Profile" eyebrow="Account / 10" description="Your farm identity, preferences, and account details." icon={CircleUserRound} />} /><Route path="*" element={<Home />} /></Routes></Shell></BrowserRouter>; }
export default App;