import { useMemo, useState } from "react";
import { BrowserRouter, NavLink, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { ArrowUpRight, Bell, Check, CheckCircle2, ChevronDown, CircleUserRound, Edit3, Eye, Filter, Home as HomeIcon, Leaf, LineChart, MapPin, Menu, MessageCircle, MoreHorizontal, Package, Plus, Search, Send, Settings, ShoppingBasket, SlidersHorizontal, Star, Store, Truck, Warehouse, X } from "lucide-react";
import "@/App.css";
import "@/Workspace.css";

const navItems = [
  ["/", "Home", HomeIcon], ["/marketplace", "Marketplace", Store], ["/prices", "Market Prices", LineChart],
  ["/produce", "My Produce", Leaf], ["/requests", "Buyer Requests", ShoppingBasket], ["/storage", "Storage", Warehouse],
  ["/transport", "Transport", Truck], ["/orders", "Orders", Package], ["/messages", "Messages", MessageCircle], ["/profile", "Profile", CircleUserRound],
];
const produce = [{ name: "Tomato", detail: "Grade A • Organic", amount: "800", place: "Farm Storage 1", icon: "nutrition", tone: "red" }, { name: "Onion", detail: "Red • Standard", amount: "500", place: "Warehouse B", icon: "psychiatry", tone: "gold" }, { name: "Potato", detail: "Russet • Premium", amount: "350", place: "Farm Storage 2", icon: "grain", tone: "stone" }];
const requests = [{ name: "Need 500 kg Tomato", detail: "Grade A Quality", meta: "Within 20 km (Delivery preferred)", time: "Posted 2 hours ago", tone: "red", verified: true }, { name: "Need 1,000 kg Onion", detail: "Standard Size", meta: "Pickup from farm", time: "Posted 5 hours ago", tone: "purple", verified: false }];

function Shell({ children }) {
  const [open, setOpen] = useState(false);
  const location = useLocation();
  return <div className="app-shell">
    <button className="mobile-menu" data-testid="mobile-menu-button" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X /> : <Menu />}</button>
    <aside className={open ? "sidebar is-open" : "sidebar"} data-testid="app-sidebar">
      <div className="brand"><div className="brand-mark"><Leaf size={18} /></div><div><strong>KrishiLink</strong><span>Agricultural Marketplace</span></div></div>
      <nav className="nav-list">{navItems.map(([to, label, Icon]) => <NavLink key={to} to={to} end={to === "/"} className={({ isActive }) => isActive ? "nav-item active" : "nav-item"} data-testid={`nav-${label.toLowerCase().replaceAll(" ", "-")}`} onClick={() => setOpen(false)}><Icon size={19} strokeWidth={1.8} /><span>{label}</span></NavLink>)}</nav>
      <button className="post-button" data-testid="sidebar-post-produce-button" onClick={() => window.location.assign("/produce?add=true")}><Plus size={18} /> Post Produce</button>
      <div className="sidebar-footer"><div className="avatar">AS</div><div><strong>Arjun Singh</strong><span>Farmer account</span></div><Settings size={16} /></div>
    </aside>
    <main className="main-content"><header className="topbar"><div className="crumb"><span>Workspace</span><ChevronDown size={14} /></div><div className="top-actions"><button data-testid="language-button" className="icon-button">EN</button><button data-testid="notifications-button" className="icon-button notification"><Bell size={19} /><i /></button><button data-testid="profile-menu-button" className="profile-trigger"><div className="avatar small">AS</div><span>Arjun Singh</span><ChevronDown size={14} /></button></div></header>{children}</main>
  </div>;
}

function PageHeader({ eyebrow, title, description, action }) { return <div className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description && <p className="page-description">{description}</p>}</div>{action}</div>; }
function Stat({ label, value, detail, tone = "green" }) { return <div className="stat" data-testid={`stat-${label.toLowerCase().replaceAll(" ", "-")}`}><div className={`stat-icon ${tone}`}><Leaf size={18} /></div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div>; }

function Home() { const navigate = useNavigate(); return <><PageHeader eyebrow="Overview / 01" title="Good morning, Arjun" description="Your harvest, marketplace activity, and next opportunities at a glance." action={<button className="primary-button" data-testid="home-post-produce-button" onClick={() => navigate("/produce?add=true")}><Plus size={18} /> Post Produce</button>} /><section className="stats-grid"><Stat label="Active stock" value="1,650 kg" detail="Across 3 produce lots" /><Stat label="Market value" value="₹82,400" detail="↑ 8.4% this week" tone="blue" /><Stat label="Open requests" value="24" detail="6 match your produce" tone="peach" /><Stat label="Next delivery" value="Tomorrow" detail="To Green Basket Co." tone="gold" /></section><div className="dashboard-grid"><section className="panel harvest-panel"><div className="section-heading"><div><p className="eyebrow">Inventory pulse</p><h2>Your produce</h2></div><NavLink to="/produce" data-testid="home-view-produce-link">View all <span>→</span></NavLink></div>{produce.map((item) => <div className="compact-row" key={item.name} data-testid={`home-produce-${item.name.toLowerCase()}-row`}><div className={`crop-icon ${item.tone}`}><Leaf size={19} /></div><div className="row-main"><strong>{item.name}</strong><span>{item.detail}</span></div><strong className="row-value">{item.amount} <small>kg</small></strong><span className="status-dot">Available</span></div>)}</section><section className="panel activity-panel"><div className="section-heading"><div><p className="eyebrow">Recent activity</p><h2>Stay in the loop</h2></div><Bell size={19} /></div>{["Tomato listing viewed by 3 buyers", "Order #KL-2048 is ready for pickup", "You matched with Green Basket Co."].map((x, i) => <div className="activity" key={x}><span className={`activity-mark mark-${i}`} /><div><strong>{x}</strong><small>{["12 minutes ago", "Yesterday, 4:30 PM", "Yesterday, 11:12 AM"][i]}</small></div></div>)}</section></div><section className="quote-band"><div><p className="eyebrow">Market insight</p><h2>“Better information makes for better harvests.”</h2><p>Tomato demand is up 12% in your region this week.</p></div><NavLink to="/prices" className="outline-button" data-testid="home-market-prices-link">Explore prices <LineChart size={16} /></NavLink></section></>; }

function Produce() { const [items, setItems] = useState(produce); const [showForm, setShowForm] = useState(false); const [sold, setSold] = useState([]); const add = () => { const name = prompt("Produce name"); if (name) setItems([...items, { name, detail: "Fresh stock", amount: "0", place: "Farm Storage 1", tone: "green" }]); }; return <><PageHeader eyebrow="Inventory / 04" title="My Produce" description={<>Total active stock: <b>1,650 kg</b></>} action={<button className="primary-button" data-testid="add-produce-button" onClick={() => { setShowForm(true); add(); }}><Plus size={18} /> Add Produce</button>} />{showForm && <div className="toast" data-testid="produce-success-message">Produce list updated <button data-testid="dismiss-toast-button" onClick={() => setShowForm(false)}>×</button></div>}<section className="produce-grid">{items.map((item) => <article className="produce-card" key={item.name}><div className="card-top"><div className={`crop-icon ${item.tone}`}><Leaf size={20} /></div><div><h3>{item.name}</h3><p>{item.detail}</p></div><span className="availability">Available</span></div><div className="amount">{item.amount} <small>kg</small></div><p className="location"><MapPin size={15} /> {item.place}</p><div className="card-actions"><button data-testid={`view-${item.name.toLowerCase()}-button`}><Eye size={16} /> View Lot</button><button className="square" data-testid={`edit-${item.name.toLowerCase()}-button`} aria-label={`Edit ${item.name}`}><Edit3 size={16} /></button></div><button className="sold-button" data-testid={`mark-${item.name.toLowerCase()}-sold-button`} onClick={() => setSold([...sold, item.name])}>{sold.includes(item.name) ? "Marked as sold" : "Mark as Sold"}</button></article>)}</section></>; }

function Requests() { const [filtered, setFiltered] = useState(requests); const apply = (e) => { e.preventDefault(); const crop = e.currentTarget.crop.value; setFiltered(crop === "All crops" ? requests : requests.filter((r) => r.name.toLowerCase().includes(crop.toLowerCase()))); }; return <><PageHeader eyebrow="Opportunities / 05" title="Buyer requests" description="Connect with buyers looking for specific produce in your area." /><form className="filter-bar" onSubmit={apply} data-testid="buyer-request-filter-form"><label>Crop type<select name="crop" data-testid="crop-type-select"><option>All crops</option><option>Tomato</option><option>Onion</option></select></label><label>Minimum quantity<input name="quantity" data-testid="minimum-quantity-input" type="number" placeholder="e.g. 100" /></label><label>Distance<select name="distance" data-testid="distance-select"><option>Within 50 km</option><option>Within 20 km</option><option>Anywhere</option></select></label><button className="secondary-button" data-testid="apply-filters-button"><Filter size={16} /> Apply filters</button></form><section className="request-grid">{filtered.map((r) => <article className="request-card" key={r.name}><div className="request-title"><div className={`crop-photo ${r.tone}`}><Leaf size={24} /></div><div><h3>{r.name}</h3><p>{r.detail}</p></div>{r.verified && <span className="verified">✓ Verified buyer</span>}</div><div className="request-meta"><span><MapPin size={16} /> {r.meta}</span><span><Bell size={15} /> {r.time}</span></div><button className="full-button" data-testid={`view-request-${r.name.split(" ").pop().toLowerCase()}-button`} onClick={() => alert(`Request details for ${r.name}`)}>View request <span>→</span></button></article>)}</section></>; }

const workspaceRows = {
  Marketplace: [{ title: "Green Basket Co.", sub: "Buyer · 12 km away", value: "Looking for 500 kg tomato", tone: "green" }, { title: "Sahyadri Organics", sub: "Seller · Pune", value: "Organic onion · ₹38/kg", tone: "gold" }, { title: "FreshRoute Foods", sub: "Buyer · 28 km away", value: "Weekly potato contract", tone: "blue" }],
  "Market Prices": [{ title: "Tomato", sub: "Grade A · Pune mandi", value: "₹42 / kg  ↑ 12%", tone: "red" }, { title: "Onion", sub: "Red · Nashik mandi", value: "₹36 / kg  ↑ 4%", tone: "purple" }, { title: "Potato", sub: "Premium · Satara mandi", value: "₹28 / kg  ↓ 2%", tone: "stone" }],
  Storage: [{ title: "Farm Storage 1", sub: "On-farm · 1.2 km away", value: "800 kg capacity used", tone: "green" }, { title: "Warehouse B", sub: "Cold storage · 8 km away", value: "500 kg capacity used", tone: "blue" }],
  Transport: [{ title: "Pickup to Green Basket Co.", sub: "Tomorrow · 09:00 AM", value: "18 km · 800 kg", tone: "gold" }, { title: "Farm to Warehouse B", sub: "Friday · 02:30 PM", value: "8 km · 500 kg", tone: "green" }],
  Orders: [{ title: "#KL-2048 · Green Basket Co.", sub: "Tomato · Delivery tomorrow", value: "₹33,600 · In transit", tone: "green" }, { title: "#KL-2041 · FreshRoute Foods", sub: "Potato · Completed 12 Jun", value: "₹9,800 · Paid", tone: "blue" }],
  Messages: [{ title: "Green Basket Co.", sub: "Last message 12 minutes ago", value: "Can we confirm the delivery window?", tone: "green" }, { title: "Sahyadri Organics", sub: "Last message yesterday", value: "Your onion listing looks great.", tone: "gold" }],
  Profile: [{ title: "Arjun Singh", sub: "Verified farmer · Maharashtra", value: "4.9 rating · 28 transactions", tone: "green" }, { title: "Farm preferences", sub: "Notifications and visibility", value: "Everything looks good", tone: "blue" }],
};

function InteractiveWorkspace({ title, eyebrow, description, icon: Icon = Package, secondary = "Browse activity" }) {
  const [tab, setTab] = useState("Overview");
  const [query, setQuery] = useState("");
  const [message, setMessage] = useState("");
  const [selected, setSelected] = useState([]);
  const rows = useMemo(() => (workspaceRows[title] || []).filter((row) => `${row.title} ${row.sub} ${row.value}`.toLowerCase().includes(query.toLowerCase())), [title, query]);
  const slug = title.toLowerCase().replaceAll(" ", "-");
  const toggle = (name) => setSelected((current) => current.includes(name) ? current.filter((x) => x !== name) : [...current, name]);
  return <><PageHeader eyebrow={eyebrow} title={title} description={description} action={<button className="primary-button" data-testid={`${slug}-primary-button`} onClick={() => setMessage(`${title} draft started`)}><Plus size={18} /> Create new</button>} />
    {message && <div className="toast" data-testid={`${slug}-success-message`}>{message}<button data-testid={`${slug}-dismiss-message`} onClick={() => setMessage("")}>×</button></div>}
    <div className="workspace-toolbar"><div className="workspace-tabs">{["Overview", "Activity", "Saved"].map((item) => <button key={item} className={tab === item ? "tab active" : "tab"} data-testid={`${slug}-${item.toLowerCase()}-tab`} onClick={() => setTab(item)}>{item}</button>)}</div><label className="search-field"><Search size={16} /><input data-testid={`${slug}-search-input`} value={query} onChange={(e) => setQuery(e.target.value)} placeholder={`Search ${title.toLowerCase()}`} /></label><button className="icon-button boxed" data-testid={`${slug}-filter-button`}><SlidersHorizontal size={17} /></button></div>
    <div className="workspace-layout"><section className="workspace-list" data-testid={`${slug}-content`}><div className="list-header"><div><p className="eyebrow">{tab} / {rows.length} items</p><h2>Stay on top of your {title.toLowerCase()}</h2></div><button className="icon-button" data-testid={`${slug}-more-button`}><MoreHorizontal /></button></div>{rows.length ? rows.map((row) => <div className="workspace-row" key={row.title} data-testid={`${slug}-row-${row.title.toLowerCase().replaceAll(" ", "-")}`}><div className={`crop-icon ${row.tone}`}><Icon size={19} /></div><div className="row-main"><strong>{row.title}</strong><span>{row.sub}</span></div><div className="workspace-value"><strong>{row.value}</strong><small>{tab === "Activity" ? "Updated recently" : "Open details"}</small></div><button className={selected.includes(row.title) ? "row-action checked" : "row-action"} data-testid={`${slug}-action-${row.title.toLowerCase().replaceAll(" ", "-")}`} onClick={() => toggle(row.title)}>{selected.includes(row.title) ? <Check size={16} /> : <ArrowUpRight size={16} />}</button></div>) : <div className="no-results"><Search size={22} /><strong>No matches found</strong><span>Try a different search term.</span></div>}</section><aside className="workspace-aside"><div className="aside-icon"><Icon size={22} /></div><p className="eyebrow">Quick action</p><h3>Make progress on your farm</h3><p>Keep this workspace current so the right people can find you faster.</p><button className="secondary-button" data-testid={`${slug}-quick-action-button`} onClick={() => setMessage(`${secondary} opened`)}>{secondary} <ArrowUpRight size={15} /></button><div className="aside-stat"><span>Profile completeness</span><strong>86%</strong><div><i /></div></div></aside></div></>;
}

function App() { return <BrowserRouter><Shell><Routes><Route path="/" element={<Home />} /><Route path="/produce" element={<Produce />} /><Route path="/requests" element={<Requests />} /><Route path="/marketplace" element={<InteractiveWorkspace title="Marketplace" eyebrow="Discover / 02" description="Find trusted buyers, sellers, and fresh opportunities." icon={Store} />} /><Route path="/marketplace/listings" element={<InteractiveWorkspace title="Marketplace" eyebrow="Discover / 02 / Listings" description="Browse the latest produce listings near you." icon={Store} />} /><Route path="/prices" element={<InteractiveWorkspace title="Market Prices" eyebrow="Signals / 03" description="Track the latest rates for crops in your region." icon={LineChart} />} /><Route path="/prices/forecast" element={<InteractiveWorkspace title="Market Prices" eyebrow="Signals / 03 / Forecast" description="See where demand is moving next." icon={LineChart} />} /><Route path="/storage" element={<InteractiveWorkspace title="Storage" eyebrow="Logistics / 06" description="Manage where your harvest is kept and cared for." icon={Warehouse} />} /><Route path="/storage/locations" element={<InteractiveWorkspace title="Storage" eyebrow="Logistics / 06 / Locations" description="Compare available farm and cold-storage space." icon={Warehouse} />} /><Route path="/transport" element={<InteractiveWorkspace title="Transport" eyebrow="Logistics / 07" description="Coordinate pickups and deliveries with confidence." icon={Truck} />} /><Route path="/transport/schedule" element={<InteractiveWorkspace title="Transport" eyebrow="Logistics / 07 / Schedule" description="Plan the next movement of your harvest." icon={Truck} />} /><Route path="/orders" element={<InteractiveWorkspace title="Orders" eyebrow="Operations / 08" description="Review every active and completed order." icon={Package} />} /><Route path="/orders/history" element={<InteractiveWorkspace title="Orders" eyebrow="Operations / 08 / History" description="Look back at your completed trade history." icon={Package} />} /><Route path="/messages" element={<InteractiveWorkspace title="Messages" eyebrow="Connections / 09" description="Stay close to the people who move your produce." icon={MessageCircle} />} /><Route path="/messages/new" element={<InteractiveWorkspace title="Messages" eyebrow="Connections / 09 / New" description="Start a conversation with a trusted marketplace contact." icon={Send} />} /><Route path="/profile" element={<InteractiveWorkspace title="Profile" eyebrow="Account / 10" description="Your farm identity, preferences, and account details." icon={CircleUserRound} />} /><Route path="/profile/settings" element={<InteractiveWorkspace title="Profile" eyebrow="Account / 10 / Settings" description="Tune your account and notification preferences." icon={Settings} />} /><Route path="*" element={<Home />} /></Routes></Shell></BrowserRouter>; }
export default App;